""" Constants for Dahua manager module """
CGI_CONFIG = '/cgi-bin/configManager.cgi'
CGI_EVENTS = '/cgi-bin/eventManager.cgi'
SCRIPT_MAGIC_BOX = '/cgi-bin/magicBox.cgi'
CGI_PTZ = '/cgi-bin/ptz.cgi'
SCRIPT_DEV_VIDEO_INPUT = '/cgi-bin/devVideoInput.cgi'

INFO_KEY_CHANNEL_NAME = 'Name'
INFO_KEY_PTZ_CAPABILITIES = 'PTZCapabilities'
INFO_KEY_PTZ_SETTINGS = 'PTZSettings'
INFO_KEY_NETWORK = 'Network'
INFO_KEY_SERIAL = 'Serial'
INFO_KEY_SOFTWARE = 'Software'
INFO_KEY_TYPE = 'Type'
INFO_KEY_MOTION_DETECT = 'MotionDetect'
INFO_MACHINE_NAME = 'MachineName'
INFO_LANGUAGES = 'Languages'
INFO_LANGUAGE = 'Language'
